#inherit_from:
#  - ~/configs/.rubocop.yml

AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - 'test/**/*'

Layout/AccessModifierIndentation:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false
Style/RescueModifier:
  Exclude:
    - 'lib/act_with_bag.rb'
