language: ruby
bundler_args: --without production
before_install: rm -f Gemfile.lock

rvm:
  - 1.9.3
  - 2.1.0

env:
  - "RAILS_VERSION=3.2.16"
  - "RAILS_VERSION=4.0.2"

notifications:
  email: false
