language: ruby
bundler_args: --without production
before_install: rm -f Gemfile.lock

rvm:
#  - 1.9.3
  - 2.2.3
  - 2.3.1

env:
#  - "RAILS_VERSION=3.2.16"  # making problems at travis
  - "RAILS_VERSION=4.2.4"
  - "RAILS_VERSION=5.0.0.1"

#matrix:
#  exclude:
#    - rvm: 2.2.3
#      env: "RAILS_VERSION=3.2.16"

notifications:
  email: false
