# under construction

name: Analyze code statically
"on": pull_request
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using Rubocop
        uses: moneyforward/rubocop-action@v0

